// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJATK_APBD_Cw7_sxxxxx.Infrastrucutre;

#nullable disable

namespace PJATK_APBD_Cw7_sxxxxx.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260517163553_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PJATK_APBD_Cw7_sxxxxx.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "CPU001",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 1,
                            Description = "14th generation processor",
                            Name = "Intel i7"
                        },
                        new
                        {
                            Code = "GPU001",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 2,
                            Description = "Gaming graphics card",
                            Name = "RTX 4070"
                        },
                        new
                        {
                            Code = "RAM001",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 3,
                            Description = "DDR5 memory",
                            Name = "Corsair 16GB"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_sxxxxx.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("foundationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INT",
                            FullName = "Intel Corporation",
                            foundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NVDA",
                            FullName = "NVIDIA Corporation",
                            foundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "CR",
                            FullName = "Corsair",
                            foundationDate = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_sxxxxx.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_sxxxxx.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast",
                            Stock = 10,
                            Warranty = 36,
                            Weight = 8.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Pro",
                            Stock = 15,
                            Warranty = 24,
                            Weight = 6.2f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workstation X",
                            Stock = 5,
                            Warranty = 48,
                            Weight = 9.1f
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_sxxxxx.Models.PCsComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCsComponents");

                    b.HasData(
                        new
                        {
                            PcId = 1,
                            ComponentCode = "CPU001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "GPU001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "RAM001",
                            Amount = 2
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "CPU001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "RAM001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "CPU001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "GPU001",
                            Amount = 2
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_sxxxxx.Models.Component", b =>
                {
                    b.HasOne("PJATK_APBD_Cw7_sxxxxx.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw7_sxxxxx.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_sxxxxx.Models.PCsComponent", b =>
                {
                    b.HasOne("PJATK_APBD_Cw7_sxxxxx.Models.Component", "Component")
                        .WithMany("PCsComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw7_sxxxxx.Models.PC", "Pc")
                        .WithMany("PCsComponents")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_sxxxxx.Models.Component", b =>
                {
                    b.Navigation("PCsComponents");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_sxxxxx.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_sxxxxx.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_sxxxxx.Models.PC", b =>
                {
                    b.Navigation("PCsComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
